"""Governance rules and non-automation boundaries."""
from src.governance.guardrails import (
    PROHIBITED_AUTOMATED_ACTIONS,
    PERMITTED_SYSTEM_SCOPE,
    ADMINISTRATIVE_ACTIVITY_PRINCIPLE,
    ABSENCE_OF_SIGNAL_PRINCIPLE,
    TWO_TIER_DISTINCTION_PRINCIPLE,
    HUMAN_FEEDBACK_AUTHORITY_PRINCIPLE,
    HUMAN_DECISION_WORKFLOW,
    get_governance_statement,
)

__all__ = [
    "PROHIBITED_AUTOMATED_ACTIONS",
    "PERMITTED_SYSTEM_SCOPE",
    "ADMINISTRATIVE_ACTIVITY_PRINCIPLE",
    "ABSENCE_OF_SIGNAL_PRINCIPLE",
    "TWO_TIER_DISTINCTION_PRINCIPLE",
    "HUMAN_FEEDBACK_AUTHORITY_PRINCIPLE",
    "HUMAN_DECISION_WORKFLOW",
    "get_governance_statement",
]



